"""Category与Article建立一对多关系

Revision ID: ad98e7b4a35d
Revises: 84f3ce657c12
Create Date: 2021-11-22 05:17:41.092781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad98e7b4a35d'
down_revision = '84f3ce657c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cate_id', sa.Integer(), nullable=False),
    sa.Column('cate_name', sa.String(), nullable=True),
    sa.Column('cate_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cate_id'),
    sa.UniqueConstraint('cate_name')
    )
    op.add_column('article', sa.Column('cate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'category', ['cate_id'], ['cate_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'cate_id')
    op.drop_table('category')
    # ### end Alembic commands ###
